### ISSUE TITLE
メニューをローカルに保存する

### ISSUE THREAD

**Issue by tarao1006** [tarao1006/kakure-handy#3]
## 概要

メニューはその日の営業中に増えたり減ったりすることは考えにくい。そのため、以前の注文からn時間以上時間が空いている時のみ、サーバーから情報を受け取って `localStorage` に保存するようにし、それ以外は、 `localStorage` からメニューを読み取るように
する。

## TODO

- [ ] メニューを `localStorage` に追加するコードを追加する。
- [ ] メニューをサーバーから読み取った時間を `localStorage` に保存するコードを追加する。
- [ ] メニューを `localStorage` から読み取るコードを追加する。
